actors:
  actionfrancaise_net:
    crawls:
    - crawl_actionfrancaise_20251003_000000
    doc_count: 2
    domains:
    - actionfrancaise_net
    global_five: far_right
    intra_left: null
    intra_right: far_right
    side_binary: right
  bernardlugan_blogspot_com:
    crawls:
    - crawl_actionfrancaise_20251003_000000
    doc_count: 1
    domains:
    - bernardlugan_blogspot_com
    global_five: left
    intra_left: left
    intra_right: null
    side_binary: left
  politiquemagazine_fr:
    crawls:
    - crawl_actionfrancaise_20251003_000000
    doc_count: 2
    domains:
    - politiquemagazine_fr
    global_five: left
    intra_left: center_left
    intra_right: null
    side_binary: left
